dependencies {
    // Sa-Token
  implementation(libs.sa.token.reactor.spring.boot3.starter) {
    exclude group: 'org.springframework.boot', module: 'spring-boot-starter-web'
  }
  // Sa-Token Redisson Configuration
  implementation(libs.sa.token.redisson.spring.boot.starter)
  // Load Balancer
  implementation(libs.spring.cloud.starter.loadbalancer) {
    exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    exclude group: 'ch.qos.logback', module: 'logback-classic'
    exclude group: 'ch.qos.logback', module: 'logback-core'
  }
  // GateWay
  implementation(libs.spring.cloud.starter.gateway) {
    exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    exclude group: 'ch.qos.logback', module: 'logback-classic'
    exclude group: 'ch.qos.logback', module: 'logback-core'
  }

  implementation(project(":common:base"))
  implementation(project(":common:limiter")) {
    exclude group: 'org.springframework', module: 'spring-web'
    exclude group: 'org.springframework', module: 'spring-webmvc'
  }
  implementation(project(":common:config"))
  implementation(project(":common:api"))
  implementation(project(":common:skywalking"))
  implementation(project(":common:prometheus"))
}