dependencies {
  implementation(project(":common:base"))
  implementation(project(":common:api"))
  implementation(project(":common:cache"))
  implementation(project(":common:config"))
  implementation(project(":common:rpc"))
  implementation(project(":common:lock"))
  implementation(project(":common:sa-token"))
  implementation(project(":common:data-source-config"))
  implementation(project(":common:web"))
  implementation(project(":common:skywalking"))
  implementation(project(":common:file"))
}