dependencies {
  implementation(project(":common:base"))
  implementation(project(":common:api"))
  implementation(project(":common:cache"))
  implementation(project(":common:config"))
  implementation(project(":common:rpc"))
  implementation(project(":common:lock"))
  implementation(project(":common:sa-token"))
  implementation(project(":common:data-source-config"))
  implementation(project(":common:web"))
  implementation(project(":common:skywalking"))
  implementation(project(":common:file"))

  // 引入WebSocket 依赖
  implementation(libs.spring.boot.starter.websocket)
  testImplementation(libs.spring.boot.starter.websocket)

  // test 框架
  testImplementation(libs.junit)
  testImplementation(libs.spring.test)
  testCompileOnly(libs.mapstruct)
  testAnnotationProcessor(libs.mapstruct.processor)
}