spring:
  application:
    name: data-engine-auth
  config:
    import: classpath:base.yml,classpath:cache.yml,classpath:rpc.yml,classpath:sa-token.yml,classpath:prometheus.yml

dubbo:
  application:
    qos-port: 20005

server:
  port: 8086