spring:
  application:
    name: data-engine-personal
    log:
      path: /root/Documents/output/dataengine
  config:
    import: classpath:base.yml,classpath:cache.yml,classpath:datasource.yml,classpath:rpc.yml,classpath:sa-token.yml

dubbo:
  protocol:
    port: 30004
  application:
    qos-port: 20004

server:
  port: 8085