spring:
  application:
    name: data-engine-admin
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:rpc.yml,classpath:cache.yml,classpath:file.yml,classpath:sa-token.yml,classpath:prometheus.yml

dubbo:
  application:
    qos-port: 20000

server:
  port: 8082